### ISSUE TITLE
Angular 9 Update?

### ISSUE THREAD

**Issue by qdouble** [enten/udk#16]
Hey...I tried to see if I can start working with Angular 9 now that it is in rc, but udk doesn't work with it. Any plans to make it compatible soon?

**Comment by enten** [comment]
@qdouble 

Hi, I already starts to work on udk to make it compatible with Angular 9.

But Angular 9 introduces some changes in the devkit which are not easy to handle in udk.

I hope to make everything work for november.

**Comment by enten** [comment]
@qdouble 

My apologies, I hadn't time in november to continue working on angular 9 support.

I worked on last week end and I hope to release angular 9 support this month.

FYI below the progress.

Tasks:

* [done] make universal builder works with angular 9
* [done] make universal dev server works with angular 9
* [done] format logging messages
* [done] re-introduce universal options
* [done] test with minimal universal project
* [done] test with real world project
* [todo] release new udk version with support for angular 9

Log:

* 2019-12-08: work on universal builder
* 2019-12-09: work on universal dev server
* 2019-12-10: work on format loggig message and re-introduce universal options
* 2019-12-11: I'm testing [udk v1.1.9-rc.0](https://www.npmjs.com/package/udk/v/1.1.9-rc.0) with [angular-universal boilerplate](https://github.com/enten/angular-universal/commit/d9e860a0deecd4711c6f41ecadcc5d9d72444093) (branch [angular/support-v9](https://github.com/enten/angular-universal/tree/angular/support-v9)). I hit issues with templateUrls and styleUrls which can't be found during SSR (inline template and styles works well) and HMR on browser side with the dev server. I will investigate soon.
* 2019-12-14: I found that bundle \@angular and \@nguniversal packages are required to make ssr works with angular on server. I released [udk v1.1.9-rc.1](https://www.npmjs.com/package/udk/v/1.1.9-rc.1) which works with angular 9.0.0-rc.6 (devkit 0.900.0-rc.6). HMR on browser is still broken but I think that is not related with udk but angular hmr package.
* 2019-12-17: I figure that HMR works on browser without any change. I think I had a bad node_modules folder due to development env of udk.

**Comment by enten** [comment]
@qdouble

I released [udk v1.1.9-rc.1](https://www.npmjs.com/package/udk/v/1.1.9-rc.1) which works with angular 9.0.0-rc.6 (devkit v0.900.0-rc.6).

_Can you try to update to angular v9.0.0-rc.6 (devkit v0.900.0-rc.6) and udk v1.1.9-rc.1 to check if angular 9 support works?_

**WARN**: some adjustements are required in your angular universal project you can [check example here](https://github.com/enten/angular-universal/commit/949e56315a650e5070a0390b48ed065025c7bb3d#diff-916156c481141bfcd08c6ae40ce10e00).

```shell
npm install @angular/animations@9.0.0-rc.6 @angular/common@9.0.0-rc.6 @angular/compiler@9.0.0-rc.6 @angular/core@9.0.0-rc.6 @angular/forms@9.0.0-rc.6 @angular/http@8.0.0-beta.10 @angular/platform-browser@9.0.0-rc.6 @angular/platform-browser-dynamic@9.0.0-rc.6 @angular/platform-server@9.0.0-rc.6 @angular/router@9.0.0-rc.6 @angularclass/hmr@2.1.3 @nguniversal/express-engine@8.2.6 @nguniversal/module-map-ngfactory-loader@v8.2.6

npm install --save-dev @angular-devkit/build-angular@0.900.0-rc.6 @angular/cli@9.0.0-rc.6 @angular/compiler-cli@9.0.0-rc.6 @angular/language-service@9.0.0-rc.6 typescript@3.6.4 udk@1.1.9-rc.1
```

**Comment by qdouble** [comment]
@enten Hey, I've been using it for like a week... it wasn't working for me at first because of dependency mismatches in my project, but everything seems fine now. I'm use rc.7 of angular with nrwl

**Comment by enten** [comment]
@qdouble 

I encountered troubleshooting with mismatches dependencies too.
In this case: remove node_modules folder, remove package-lock.json and run `npm install` fix that.

I will wait for angular v9 first release to check the angular devkit behavior with udk builders.
When everythings will work well, I will publish udk v1.1.9.

**Comment by enten** [comment]
@qdouble 

We experiment udk with angular v9 since few months now without any issue.

Is it okay for you? Can we close this issue?
